name: job_recommender_app
description: Hybrid job recommendation Flutter client for the JobStreet dataset
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  provider: ^6.0.5
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
